#!/usr/bin/env python3
"""Regenerate the coverage map: what holds each rule, and what exercises each holder.

A hand-kept coverage table lies within a release — it is written once, believed for months, and
nobody notices the suite it names was renamed in between. This one is assembled from the tree
itself: every `enforced_by` the corpus states, every validator and hook that ships, every test
suite beside them, every scenario in the rubric and every run recorded against a version.

**Rates are deliberately not copied here.** They live dated in `evals/runs/<version>.md`, and a
rate copied into a second file is a stale claim the moment the next round runs — the failure
this generator exists to refuse, reproduced by hand.

Usage: python3 scripts/coverage-map.py   (from the repo root; writes evals/COVERAGE.md)
"""
import glob
import subprocess
import re
from collections import Counter
from pathlib import Path

OUT = Path("evals/COVERAGE.md")


def first_comment(path):
    """The file's own one-line self-description — its first comment or docstring line."""
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if s.startswith("#!") or not s:
            continue
        if s.startswith("#"):
            return s.lstrip("# ").rstrip(".")
        if s.startswith('"""'):
            return s.strip('"').rstrip(".")
        break
    return ""


def main():
    enforced = Counter()
    for f in glob.glob("*.md") + glob.glob("templates/*.md"):
        for m in re.finditer(r"`?enforced_by[:\s]+`?\s*([a-z-]+)",
                             Path(f).read_text(encoding="utf-8", errors="replace"), re.I):
            enforced[m.group(1).lower()] += 1

    validators = [(f, first_comment(f)) for f in sorted(glob.glob("scripts/*.py"))
                  if not Path(f).name.startswith("test")]
    # Only the `.py`: each hook ships with a one-line `.sh` shim that carries no docstring, and
    # listing both doubled the count while adding a blank description per pair.
    hooks = [(f, first_comment(f)) for f in sorted(glob.glob("hooks/*.py"))]
    tests = [(f, first_comment(f)) for f in
             sorted(glob.glob("scripts/test-*.sh") + glob.glob("scripts/tests/test_*.py"))]

    rubric = Path("evals/README.md").read_text(encoding="utf-8", errors="replace")
    scenarios = re.findall(r"^## (\d+)\.\s+(.+)$", rubric, flags=re.M)
    runs = sorted(p for p in glob.glob("evals/runs/*.md") if "TEMPLATE" not in p)

    # **A scenario is only runnable if its situation can be built.** Two halves, and they are
    # tracked separately because a round measured the wrong thing when only one existed: the
    # repository half (a tree the player stands in) and the workspace half (a board built by
    # `eval-fixture.py`). A scenario with neither can still be run if it needs no state; a
    # scenario that needs state and has none is the void this column exists to make visible.
    builders = set(re.findall(r'^BUILDERS = \{(.*?)\}', Path("scripts/eval-fixture.py")
                              .read_text(encoding="utf-8", errors="replace"), re.S | re.M)[0:1])
    have_builder = set(re.findall(r'"(\d+)":', "".join(builders)))
    # **The guard's definition, not a directory-exists test.** eval-run.sh counts TRACKED files
    # under evals/fixtures/<id>/ beyond FIXTURE.md; this counted any directory, so a folder
    # holding nothing but a prose stub was reported as a provisioned half. That disagreement was
    # repaired once by hand-editing the GENERATED file — which the generator overwrote at the
    # next run. Measured 2026-08-21 (pass twelve): one definition, read from git, in both places.
    _tracked = subprocess.run(["git", "ls-files", "-z", "--", "evals/fixtures"],
                              capture_output=True, text=True).stdout.split("\0")
    # evals/fixtures/<id>/<file> is four parts; anything deeper is a real file by construction.
    # `len(parts) > 3` alone was WRONG and is worth keeping as a comment: it is true for a lone
    # FIXTURE.md too, which reinstates the exact defect this replaced. The critic walked into the
    # same shape and caught it by running it; so did this.
    have_repo = {parts[2] for parts in (f.split("/") for f in _tracked if f)
                 if len(parts) > 4 or (len(parts) == 4 and parts[3] != "FIXTURE.md")}
    ran = set()
    for r in runs:
        body = Path(r).read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"^\|\s*(\d+)\s*\|[^|]*\|\s*([^|]*)\|", body, re.M):
            if "not run" not in m.group(2).lower():
                ran.add(m.group(1))

    L = ["# Coverage — what holds each rule, and what exercises each holder",
         "",
         "*Generated by `scripts/coverage-map.py` from the tree itself — edit the tree, not "
         "this file.*",
         "",
         "**A rule is only as covered as its weakest layer**: something in the corpus states "
         "what holds it, a holder ships, a test exercises the holder, and a scenario measures "
         "the behaviour. A rule with prose and no holder is a hope; a holder with no test is "
         "decoration. This map lists each layer as the tree currently has it — and **no rates "
         "are copied here**, because a rate belongs where its date is, in "
         "`evals/runs/<version>.md`.",
         "",
         "## What the corpus says holds its rules",
         ""]
    if enforced:
        L += [f"- `{k}` — stated {v}×" for k, v in enforced.most_common()]
    else:
        L += ["- *(nothing states an `enforced_by` yet — the enum and the per-runtime honesty "
              "table are owed)*"]
    L += ["", "## Validators that ship", ""]
    L += [f"- `{n}` — {d}" for n, d in validators]
    L += ["", "## Hooks that ship", ""]
    L += [f"- `{n}` — {d}" for n, d in hooks]
    L += ["", "## Tests that exercise the holders", ""]
    L += [f"- `{n}` — {d}" for n, d in tests]
    L += ["", "## Fixtures — what a scenario can be run against", "",
          "| # | Scenario | repo half | workspace half | ever run |",
          "|---|---|---|---|---|"]
    for num, title in scenarios:
        L.append(f"| {num} | {title.strip()[:52]} | "
                 f"{'yes' if num in have_repo else '—'} | "
                 f"{'yes' if num in have_builder else '—'} | "
                 f"{'yes' if num in ran else '**no**'} |")
    L += ["", f"**{len(have_repo)} of {len(scenarios)}** carry a repository fixture, "
              f"**{len(have_builder)}** a workspace builder, and **{len(ran)}** have been "
              "measured at least once. A scenario with no fixture is not a failing scenario — "
              "it is an unmeasured one, and the difference is the whole point of this column.",
          "",
          "## Behavioural scenarios", "",
          f"- **{len(scenarios)} scenarios** in the rubric (`evals/README.md`)",
          f"- **{len(runs)} recorded runs**: "
          + " · ".join(f"`{Path(r).stem}`" for r in runs),
          "- A minor or major is not tagged without a run record for its own version "
          "(AGENTS.md → *Cutting a release*); `not run` is listed rather than omitted.",
          ""]
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT} — {len(enforced)} enforcement kinds · {len(validators)} validators · "
          f"{len(hooks)} hooks · {len(tests)} test suites · {len(scenarios)} scenarios "
          f"({len(ran)} measured, {len(have_repo)} with a fixture) · "
          f"{len(runs)} runs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
